---
# This playbook prints a simple debug/test message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: Hai, Hello, world!
      
- name: PLAYBOOK - Arista Test
  hosts: EOS

  tasks:

  - name: run show version on remote devices
    arista.eos.eos_command:
      commands: show version
