name: Ansible CD
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get list of changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Get file diffs (details)
        run: git diff HEAD~1

      - name: List all changed files
        run: |
          echo "List of files changed:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done
          
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.10.2
        # optional:
        # with:
        #   path: "playbooks/"  # <-- only one value is allowed