name: Ansible Lint # feel free to pick your own name
on: [push, pull_request]

env:
  GIT_TEST_DEBUG_UNSAFE_DIRECTORIES: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Setup global
      #   run: |
      #     git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git log
      - run: git diff HEAD~1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      # - uses: technote-space/get-diff-action@v6
      #   with:
      #     CHECK_ONLY_COMMIT_WHEN_DRAFT: true

      # - name: Diff files
      #   run: |
      #     git diff

      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible/ansible-lint-action@v6.10.2
        # optional:
        # with:
        #   path: "playbooks/"  # <-- only one value is allowed