name: Ansible Lint # feel free to pick your own name
on: [push, pull_request]

env:
  GIT_TEST_DEBUG_UNSAFE_DIRECTORIES: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup global
        run: |
          git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v3

      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible/ansible-lint-action@v6.10.2
        # optional:
        # with:
        #   path: "playbooks/"  # <-- only one value is allowed